Add docker
pol-yap/java-shareit pull request #4
Opened 2022-12-08 14:48 UTC by pol-yap

2022-12-08 18:19 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-08 18:19 UTC, FanaticFiz commented on gateway/pom.xml
> +<!--        <dependency>-->
Не оставляем мусор в коде, если что git всё помнит!

2022-12-08 18:19 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +//	@GetMapping
нуууу ваще!! ))

2022-12-08 18:19 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/common/ErrorHandler.java
> +    public ResponseEntity<ErrorMessage> handleIllegalArgumentException(IllegalArgumentException e) {
Было бы не плохо логировать когда происходит ошибка...

2022-12-08 18:19 UTC, FanaticFiz commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Валидация должна быть подключена только к одному из сервисов!

2022-12-08 18:19 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        log.trace("Created booking: " + booking);
на уровне trace ооочень много мусора... 
Обычно используют info/debug

2022-12-08 18:19 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        log.trace(String.format("Booking id=%d status changed to %s", booking.getId(), booking.getStatus()));
В логере нет нужды использовать `String.format` в нём уже есть то что тебе нужно: `{}`
`log.info("id: {}", id)`

2022-12-08 18:19 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (from < 0 || size <= 0) {
Эта проверка должна была быть сделана еще на уровне контроллера. 
Это его зона ответственности - валидировать входные параметры.
А в сервис как раз может уже идти `Pageable pageable`

2022-12-08 18:19 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingDtoCreate.java
> +    @NotNull(message = "Booking start date shouldn't be empty")
Повторюсь, валидация только в `gateway` сервисе...

2022-12-08 18:26 UTC, pol-yap commented on gateway/src/main/java/ru/practicum/shareit/common/ErrorHandler.java
> +    public ResponseEntity<ErrorMessage> handleIllegalArgumentException(IllegalArgumentException e) {
Привет!
Там же ниже, в 30 строке log.warn

2022-12-08 18:37 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/common/ErrorHandler.java
> +    public ResponseEntity<ErrorMessage> handleIllegalArgumentException(IllegalArgumentException e) {
о_О вот это я дал ))

2022-12-08 18:39 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/common/ErrorHandler.java
> +    public ResponseEntity<ErrorMessage> handleIllegalArgumentException(IllegalArgumentException e) {
Ну тогда давай его прокачаем! ))
Нам бы крайне желательно зологировать еще и со стектрейсом, передавая `e`
`log.warn("Что то пошло не так: {}", msg, e)`

2022-12-08 19:45 UTC, pol-yap commented on gateway/src/main/java/ru/practicum/shareit/common/ErrorHandler.java
> +    public ResponseEntity<ErrorMessage> handleIllegalArgumentException(IllegalArgumentException e) {
Сделал, но... в общем, здесь обрабатывается только нарушение валидации. И стектрэйс, который показывает, как там этот эксепшн бродил в недрах спринта не показался мне особо информативным.

2022-12-08 19:45 UTC, pol-yap commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
да, наверное

2022-12-08 19:45 UTC, pol-yap commented on server/src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        log.trace("Created booking: " + booking);
поменял

2022-12-08 19:45 UTC, pol-yap commented on server/src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        log.trace(String.format("Booking id=%d status changed to %s", booking.getId(), booking.getStatus()));
да, спасибо, я поздненько об этом узнал)

2022-12-09 06:21 UTC, FanaticFiz approved these changes

2022-12-09 06:21 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/item/ItemService.java
> +        log.info("Created item: " + item);
В логере нет места конкатенации...
Всегда используй подстановку по шаблону: `log.info("Created item: {}", item);`
Просто привыкай, да и среда будет тебе подсказывать если ты, в сложном логе, забудешь или ошибешься с кол-вом параметров.

2022-12-09 06:21 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        return service.findById(userId, id);
Желательно в разделять... в сервисах использовать глагол: `get`, а в `dao` - `find`

2022-12-09 16:31 UTC, merged